.TH MATHMLVIEWER "1" "May 2001" "GtkMathView" FSF
.SH NAME
mathmlviewer \- a viewer for MathML documents
.SH SYNOPSIS
.B mathmlviewer
[\fIOPTION\fR]... \fIFILE\fR...
.SH DESCRIPTION
.TP
\fB\-v\fR, \fB\-\-version\fR
Output version information
.TP
\fB\-d\fR, \fB\-\-debug\fR
Debug mode
.TP
\fB\-h\fR, \fB\-\-help\fR
This small usage guide
.TP
\fB\-\-verbose\fR[=\fI0\-3\fR]
Display messages
.SH AUTHORS
Written by Luca Padovani.
.SH "REPORTING BUGS"
Report bugs to <luca.padovani@cs.unibo.it>.
.SH "SEE ALSO"
The full documentation for
.B mathmlviewer
is maintained in the Texinfo manual for
.B gtkmathview
. If the
.B info
program and the
.B GtkMathView
library are properly installed at your site, the command
.IP
.B info gtkmathview
.PP
should give you access to the complete manual.
