.TH MATHML2PS "1" "May 2001" "GtkMathView" FSF
.SH NAME
mathml2ps \- MathML to PostScript conversion utility
.SH SYNOPSIS
.B mathml2ps
[\fIOPTION\fR]... \fIFILE\fR...
.SH DESCRIPTION
.TP
\fB\-v\fR, \fB\-\-version\fR
Output version information
.TP
\fB\-h\fR, \fB\-\-help\fR
This small usage guide
.TP
\fB\-u\fR, \fB\-\-unit=\fR<unit>
Unit for dimensions (default='cm')
.TP
\fB\-g\fR, \fB\-\-size=\fR<float>x<float>
Page size (width x height) (default = 21 x 29.7)
.TP
\fB\-m\fR, \fB\-\-margins=\fR<float>x<float>
Margins (top x left) (default = 2 x 2)
.TP
\fB\-f\fR, \fB\-\-font\-size=\fR<float>
Default font size (in pt, default=10)
.TP
\fB\-k\fR, \fB\-\-kerning[\fR=\fIyes\fR|no]
Enable/disable kerning (default='no')
.TP
\fB\-c\fR, \fB\-\-colors[\fR=\fIyes\fR|no]
Enable/disable colors (default='no')
.TP
\fB\-s\fR, \fB\-\-subset[\fR=\fIyes\fR|no]
Enable/disable font subsetting (default='yes')
.TP
\fB\-r\fR, \fB\-\-crop[\fR=\fIyes\fR|no]
Enable/disable cropping to bounding box (default='yes')
.TP
\fB\-i\fR, \fB\-\-show\-missing[\fR=\fIyes\fR|no]
If enabled show missing characters (default='yes')
.TP
\fB\-b\fR, \fB\-\-line\-breaking[\fR=\fIyes\fR|no]
Enable/disable line breaking (default='no')
.TP
\fB\-e\fR, \fB\-\-show\-empty\-rows[\fR=\fIyes\fR|no]
Show empty boxes for inferred mrows with no content (default='no')
.TP
\fB\-\-config=\fR<path>
Configuration file path
.TP
\fB\-\-verbose\fR[=\fI0\-3\fR]
Display messages
.SH "AUTHORS"
Written by Luca Padovani.
.SH "REPORTING BUGS"
Report bugs to <luca.padovani@cs.unibo.it>.
.SH "SEE ALSO"
The full documentation for
.B MathML
is maintained as a Texinfo manual.  If the
.B info
program and the
.B GtkMathView
library are properly installed at your site, the command
.IP
.B info gtkmathview
.PP
should give you access to the complete manual.
