/* Copyright (C) 2000-2007, Luca Padovani <padovani@sti.uniurb.it>.
 *
 * This file is part of GtkMathView, a flexible, high-quality rendering
 * engine for MathML documents.
 * 
 * GtkMathView is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * GtkMathView is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <stdio.h>
#include <string.h>

char buffer[257];

int main(int argc, char* argv[])
{
  printf("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\n");
  printf("<!DOCTYPE dictionary SYSTEM \"%s\">\n", argv[1]);
  printf("<!-- WARNING: DO NOT EDIT THIS FILE\n\
  This file is generated automatically from dictionary.in, which in\n\
  turn is extracted from the MathML specification.\n\
  In case it is needed to add more operators to the dictionary, edit\n\
  the file dictionary-local.xml or create a new dictionary. -->\n");
  printf("<dictionary>\n");
  while (!feof(stdin)) {
    unsigned len;

    fgets(buffer, 256, stdin);
    
    len = strlen(buffer);
    if (len > 0 && buffer[0] != '#') {
      if (buffer[len - 1] == '\n') buffer[len - 1] = '\0';
      printf("  <operator name=%s/>\n", buffer);
    }
  }
  printf("</dictionary>\n");
  
  return 0;
}

