/* Copyright (C) 2000-2007, Luca Padovani <padovani@sti.uniurb.it>.
 *
 * This file is part of GtkMathView, a flexible, high-quality rendering
 * engine for MathML documents.
 * 
 * GtkMathView is free software; you can redistribute it and/or modify it
 * either under the terms of the GNU Lesser General Public License version
 * 3 as published by the Free Software Foundation (the "LGPL") or, at your
 * option, under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation (the "GPL").  If you do not
 * alter this notice, a recipient may use your version of this file under
 * either the GPL or the LGPL.
 *
 * GtkMathView is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the LGPL or
 * the GPL for more details.
 * 
 * You should have received a copy of the LGPL and of the GPL along with
 * this program in the files COPYING-LGPL-3 and COPYING-GPL-2; if not, see
 * <http://www.gnu.org/licenses/>.
 */

#include <stdio.h>
#include <string.h>

char buffer[257];

int main(int argc, char* argv[])
{
  printf("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\n");
  printf("<!DOCTYPE dictionary SYSTEM \"%s\">\n", argv[1]);
  printf("<!-- WARNING: DO NOT EDIT THIS FILE\n\
  This file is generated automatically from dictionary.in, which in\n\
  turn is extracted from the MathML specification.\n\
  In case it is needed to add more operators to the dictionary, edit\n\
  the file dictionary-local.xml or create a new dictionary. -->\n");
  printf("<dictionary>\n");
  while (!feof(stdin)) {
    unsigned len;

    fgets(buffer, 256, stdin);
    
    len = strlen(buffer);
    if (len > 0 && buffer[0] != '#') {
      if (buffer[len - 1] == '\n') buffer[len - 1] = '\0';
      printf("  <operator name=%s/>\n", buffer);
    }
  }
  printf("</dictionary>\n");
  
  return 0;
}

