#!/bin/sh

ELIST=`cat $1 | fgrep td | cut -d '>' -f 2 | cut -d '<' -f 1`
CLIST=`cat $1 | fgrep td | cut -d '>' -f 4 | cut -d '<' -f 1`

rm -f /tmp/elist
for e in $ELIST
do
	echo '"'$e'"' >>/tmp/elist
done

rm -f /tmp/clist
for c in $CLIST
do
	echo 0x$c >>/tmp/clist
done

paste -d ',' /tmp/elist /tmp/clist
